# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Autenticando o usuario Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Construindo a imagem e enviando para o docker hub
        uses: docker/build-push-action@v3.1.1
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            rafaelmagus/kube-news:latest
            rafaelmagus/kube-news:${{github.run_number}}
  CD:
     runs-on: ubuntu-latest
     needs: [CI]
     steps:
       - uses: actions/checkout@v3
       - name: Definindo o Kube config
         uses: Azure/k8s-set-context@v2
         with:
           method: kubeconfig
           kubeconfig: ${{secrets.k8s_CONFIG}}
           
       - name: Efetunado o Deploy no kubernetes
         uses: Azure/k8s-deploy@v4.3
         with:
            images: |
              rafaelmagus/kube-news:${{github.run_number}}
            manifests: |
              k8s/deployment.yaml
     
